Fixes conf ida
gitoleg/opam-repository pull request #2
Opened 2020-07-13 18:23 UTC by gitoleg

2020-07-14 13:11 UTC, ivg requested changes
Looks good, but do not search in PATH, it is already searched by `which`. If you're also searching in PATH in the corresponding binutils patch, please update it also.

2020-07-14 13:11 UTC, ivg commented on packages/conf-ida/conf-ida.0.2/files/find-ida.ml.in
> +  match List.find_opt ~f:contains_ida64 @@ all_pathes () with
it is `paths` not `pathes`

2020-07-14 13:11 UTC, ivg commented on packages/conf-ida/conf-ida.0.2/files/find-ida.ml.in
> +  match List.find_opt ~f:contains_ida64 @@ all_pathes () with
You shouldn't be searching in the `PATH` constituents, you shall use `which` for that. Use linear search only for paths, that are not in `PATH`.

2020-07-21 17:07 UTC, ivg requested changes
1. batch up my suggestions and commit them (then fix any errors I missed)
2. incorporate the `paths` function into the loop and count _all_ entries in the directory for the total maximum

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +let idas = [ ida7; ida6; ]
there is no need to introduce extra variables, they only increase the cognition burden and, in fact are wrongly named, `ida6` is also `ida5`, `ida4`, and so on, and `ida7` could also become `ida8`, `ida9`, etc. 
```suggestion
let ida = [ "ida64"; "idaq64"]
let ida_apps = ["ida64.app"; "ida.app"]
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +let name64 x = x ^ "64"
an extra and totally unnecessary complexity
```suggestion
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +  first_success @@ List.map idas ~f:(fun ida -> which (name64 ida))
```suggestion
  first_success @@ List.map idas ~f:which
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +          file = name64 ida))
```suggestion
      List.exists idas ~f:(List.mem file idas))
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +        if is_dir path' then path' :: acc
having `path'` instead of `path` presumes that `path` is used later. 
```suggestion
        let path = path / p in
        if is_dir path then path :: acc
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +let total = 1024
```suggestion
let max_paths = 1024
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +    if depth = max_depth || entries >= total then None
```suggestion
    if depth > max_depth || entries > max_paths then None
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +      let dirs = folders path in
A folder may easily contain thousands of entries, remove the `folders` function and check if the path is a directory inside the `loop` function. You should also count _all_ entries, including folders and files, to the total maximum number of paths. 

E.g., you can easily hit a folder that has a million of entries, a directory that has an infinite number of paths (e.g., when they are generated on the fly).

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +          ~f:(loop (depth + 1) (entries + List.length dirs))
again, there could be millions of entries in dirs, so calling `List.length` should be avoided, especially since you can easily incorporate the counting of paths inside your `loop` function.

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +      check (name64 ida) || check ida)
```suggestion
let is_ida_app path =
  List.exists ida_apps ~f:(Filename.check_suffix path)
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +  match find path is_app with
```suggestion
  match find path is_ida_app with
```

2020-07-21 17:07 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +    if Sys.file_exists path' then Some path'
```suggestion
    let path = path / "Contents/MacOS/" in
    if is_dir path then Some path
```

2020-07-22 16:44 UTC, ivg approved these changes
So, first of all, I really like the code, you caught the right idea of developing a DSL (a set of small functions) and expressing the logic using those small functions. 

I have several style suggestions, feel free to accept or reject them at your discretion.

2020-07-22 16:44 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +      match next dir with
```suggestion
    else match next dir with
```

2020-07-22 16:44 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +            match opendir path with
```suggestion
        else begin match opendir path with
```

2020-07-22 16:44 UTC, ivg commented on packages/conf-ida/conf-ida.0.3/files/find-ida.ml.in
> +        match f t.(i) with
```suggestion
      else match f t.(i) with
```

2020-07-22 17:04 UTC, ivg commented
Besides, are CI failures at all relevant?

2020-07-22 17:07 UTC, gitoleg commented
well, `travis` still don't have any IDA installed, so no surprises tests fail

2020-08-04 13:54 UTC, merged